### ISSUE TITLE
Crosstab second sheet download functional? 

### ISSUE THREAD

**Issue by pabdavis** [RCL-Loren/ncdhhs-scraper#1]
hey, 

do you know if you're code works on getting the 2nd sheet of a crosstab download? 

I'm looking to download the 'TABLE_COUNTY' sheet which is alphabetically 2nd to the 'DATE' of this workbook: 

https://public.tableau.com/views/NCDHHS_COVID-19_DataDownload/CountyCasesandDeaths

Also, if there is only a single sheet, you can add a '.csv' which will export the entire sheet for you - as example, but this will download the 1st sheet:  

https://public.tableau.com/views/NCDHHS_COVID-19_DataDownload/DailyCasesandDeathsMetrics.csv 

Thanks

**Comment by RCL-Loren** [comment]
When you say "2nd sheet" do you mean the views with the radio button like "Prior Day" etc?

![image](https://user-images.githubusercontent.com/15079039/99458316-50f37680-28fa-11eb-897d-1166756d83c3.png)

**Comment by pabdavis** [comment]
Yeah, I believe those options, created a 'sheet' called Date in mid-Oct. Prior to that we were able to use the .csv extension and download the csv format via a url. 

Manually -> Export Icon -> Crosstab will bring you to the below option screen. 

![ncdhhs-county-crosstab](https://user-images.githubusercontent.com/5494292/99458725-fc9cc680-28fa-11eb-9f48-26714f1d373b.png)

**Comment by RCL-Loren** [comment]
This code is very crude right now and needs to modified to get the tab you want by modifying line 10 to select your tab.

Then you would need to add code to select the radio button. This involves opening the developer tools in Chrome, and finding the radio button XPATH and selecting it before the code that selects the download runs.  The insertion point for that is around line 19.

**Comment by RCL-Loren** [comment]
oh wait - I misunderstood. If you wanted to select the other sheet in the crosstable dialog, would need to navigate to that dialog, and find the XPATH using chrome developer toolbar and select that tab - that selection should happen just before selecting and pressing the DL button - insert at line 28

**Comment by RCL-Loren** [comment]
Now if NC DHHS would only start including Deaths by Date of Death instead of  a stupid incrementing total...

**Comment by RCL-Loren** [comment]
Let me know if that works for you.
